package com.mikmy.meldpdf

import android.app.Activity
import android.graphics.Color
import android.os.Bundle
import android.view.View

/**
 * Minimal launch surface generated by the scaffolder so the project compiles
 * and CI goes green on day one. Replace the content view with your real game
 * surface (a SurfaceView/Canvas render loop for real-time games, or a Compose
 * setContent for menu-driven apps). See references/architecture.md.
 *
 * The `baseline` intent extra is honoured by the emulator smoke test to measure
 * the cost of an empty frame; wire it into your render loop when you add one.
 */
class MainActivity : Activity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val baseline = intent?.getBooleanExtra("baseline", false) ?: false
        val root = View(this).apply {
            setBackgroundColor(if (baseline) Color.BLACK else Color.parseColor("#0B0B14"))
        }
        setContentView(root)
    }
}
